export const blogPosts = [];

for(let i=0; i<3; i++){
	 if(i==1) {
		blogPosts.push({
			id: (i+1),
			title: 'Blog'+ (i+1),
			summaryText: 'Yoda, a Force-sensitive male being belonging to a mysterious species, was a legendary Jedi Master who witnessed the rise and fall of the Galactic Republic, followed by the rise of the Galactic Empire. Small in stature but revered for his wisdom and power, Yoda trained generations of Jedi, ultimately serving as the Grand Master of the Jedi Order. Having lived through nine centuries of galactic history, he played integral roles in the Clone Wars, the rebirth of the Jedi through Luke Skywalker, and unlocking the path to immortality.',
			content:'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Born in 896 BBY, Yoda was almost nine hundred years old in the latter days of the Republic.</p>'+ 
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">A leading member of the Jedi High Council, his contemporaries included other legendary Masters such as Mace Windu and Ki-Adi-Mundi.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">During the Invasion of Naboo in 32 BBY, the maverick Qui-Gon Jinn introduced Anakin Skywalker to the High Council, believing with absolute certainty that he had discovered the prophesied Chosen One.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">The Jedi elders sensed that the boy was full of fear and anger and declined to train him, deeming Skywalker too old and emotionally compromised to commit himself to the Jedi Code.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">After Jinn death during the liberation of Naboo, the High Council reversed their decision in spite of Yoda continued opposition to Skywalker apprenticeship.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Aware of the Rule of Two, Yoda was convinced that at least one more Sith Lord remained active following Obi-Wan Kenobi victory over the Sith apprentice Darth Maul.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Unable to defend the entire Republic on their own, the Jedi took command of the newly-formed Grand Army of the Republic, with Yoda himself leading an army of clone troopers against the Separatist Droid Army of the Confederacy of Independent Systems in the first battle of the Clone Wars.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">A year later, with his health rapidly declining, Yoda died of old age and became one with the Force in 4 ABY, shortly before Luke redeemed his father Anakin, who fulfilled his destiny as the Chosen One by killing Sidious.</p>'+
			'<a href = "https://starwars.fandom.com/wiki/Yoda" target ="blank">Click here to visit Polygon website</a>',	
			imageUrl : '/data/images/Blog'+(i+1)+'.jpg'
		})}
	else if(i==2) {
	blogPosts.push({
		id: (i+1),
		title: 'Blog'+ (i+1),
		summaryText: 'Shinnosuke Nohara (野原しんのすけ), also known as Shin-chan or Shin, is the protagonist of Crayon Shin-chan. He is the son of Hiroshi and Misae. His nickname is "Shin-chan" Nohara and he is Himawari brother, a kindergarten-aged boy whose antics are the basis for the series.He is 5 years old and yet acts overtly mature. In general, he is brutally honest, highly curious, and has no shame whatsoever. Ironically, there have been several instances in which Shinnosuke own crazy antics actually solved the problems of those around him. Whether this is the result of his own or purely accidental is debatable. Adding to that, he also displays a surprising amount of talent and ability in various activities (running, surfing, kendo, fishing, skiing, swimming and others).',
		content:'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Shinnosuke is based on the character Shinnosuke Nikaido of another series by Yoshito Usui, Darakuya Store Monogatari.</p>'+ 
		'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">He is a naughty child around which the series is made. He balks at washing dishes and taking out the dog.</p>'+
		'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">What is most interesting, though not as far-out as the other differences, is that he rarely screams, rarely cries or throws tantrums, and is often punished.</p>'+
		'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">“His works are always done by his puppy dog eyes. He generally pulls his pants down when happy and dances while singing "Buri! Buri!" (ケツだけ星人).</p>'+
		'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">He is a very good singer and a pretty good baseball and football player. He learned photography from his aunt Musae.</p>'+
		'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Shin-chan mother from Kyushu. She is 29 and a typical housewife of post-war Japan. Although he always teases his mother along with his father and sister (he teases the most), he is very close with his mom, as seen when his mom goes to the hospital when she is pregnant and he becomes sad for her believing she will die in one month.</p>'+
		'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">He and his father both like to see and flirt with pretty young ladies which always get punished by his mother, Misae at the right time. Normally Shin-chan will tell things about Hiroshi to Misae, making Misae beat him up.</p>'+
		'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">He sometimes bicker with his sister but he takes care of her too.</p>'+
		'<a href = "https://crayonshinchan.fandom.com/wiki/Shinnosuke_Nohara" target ="blank">Click here to visit Polygon website</a>',	
		imageUrl : '/data/images/Blog'+(i+1)+'.jpg'
	})}
	else {
		blogPosts.push({
			id: (i+1),
			title: 'Blog'+ (i+1),
			summaryText: ' The Black Panther joined the Avengers in 1968, where he became a mainstay for the next several years. Although the character predated the revolutionary political organization of the same name, Marvel briefly changed the Black Panther’s name to the Black Leopard in an attempt to dissociate the two. A short time later he was back to being the Black Panther again, and in 1973 he headlined his own book for the first time. The “Panther’s Rage” story arc ran for two years in Jungle Action, a series written by Don McGregor and drawn for the most part by the African American artist Billy Graham. Reflecting the times’ interest in African roots and Black consciousness in general, the strip returned T’Challa to a Wakanda riven by infighting and sedition, where he managed to balance superheroics with musings on colonialism and democracy. For the duration of the tale, the strip featured an all-Black cast, something that had never before been attempted in mainstream superhero comics, and the innovations continued in a later story, which saw the Panther take on the Ku Klux Klan.',
			content:'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">In 1998 writer Christopher Priest reintroduced the hero as part of the slightly more adult “Marvel Knights” line, in a critically acclaimed series that continued until 2003.</p>'+ 
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">For this reinvention, a now aging T’Challa returns to the urban jungle of New York in a deftly written political thriller that balances intrigue with no small amount of humour.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Priest run on the comic introduced the Dora Milaje, a team of female bodyguards drawn from all the tribes of Wakanda.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">The shared storytelling palette known as the Marvel universe was unveiled in 1961, when Goodman responded to the growing interest in superhero books by commissioning writer Stan Lee and artist Jack Kirby to create the Fantastic Four.</p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">The late 1960s and early 1970s saw a new generation of creative talent emerge at Marvel. </p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">In 1967 Jim Steranko began to write and draw stories featuring secret agent Nick Fury in the anthology book Strange Tales. Steranko was influenced in his work by James Bond films and the psychedelic and Op art movements, and the resulting stories melded groundbreaking visuals with equally innovative storytelling techniques. </p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">In 1985 Mark Gruenwald started a critically acclaimed 10-year run as the writer of Captain America. </p>'+
			'<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Each of those titles was canceled after just six issues, however, because of low sales.</p>'+
			'<a href = "https://www.britannica.com/topic/Black-Panther-comic-book-character" target ="blank">Click here to visit Polygon website</a>',	
			imageUrl : '/data/images/Blog'+(i+1)+'.jpg'
		})}
}
	